### ISSUE TITLE
[Bugs] Submitted Test Cases

### ISSUE THREAD

**Issue by ArthDh** [Siddarth-M/NYCTaxi#1]
1) Pandas 1 :
df.equals() returns false for a program that works, it might have something to do with the fact that you are creating an extra column ' '
2) Pandas 2:
This doesn't make sense:
assert set('month-yr').issubset(x.columns) and x['month-yr'].dtypes == str
3) Rational Number:
from reference import Rational_Ref  -> Undefined import
Also, we wanted to check how you tested your own code using test cases. You may not always have a reference.
4) Rational Square Root:
Missing math import, the functional tests don't run. 
SyntaxError: unexpected EOF while parsing
Always test your code before submitting.
also abs_tol should have been converted back to float for a comparision

**Comment by Siddarth-M** [comment]
Thank you for the comments! For the rational square root, I had imported math in my local environment and forgot to add that in the notebook file. This is corrected now. Also, abs_tol was not converted to float in the first few test cases and that wouldn't have worked. That is also corrected now. I'll let my teammates know about the other cases. Thank you for the comments!
